### PR TITLE
feat(core): add a schema for policy files

### PR DESCRIPTION
**Pull request by boneskull**
Thought this might come in handy.  Needs titles, descriptions and such.

[This](https://snowplow.io/blog/introducing-schemaver-for-semantic-versioning-of-schemas/) seems like a reasonable idea for schema versioning.

To test in VS Code, you can add this property to any policy file:

```json
"$schema": "https://raw.githubusercontent.com/boneskull/LavaMoat/boneskull/policy-schema/packages/core/schema/lavamoat-policy.v0-0-1.schema.json"
```

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* main
  * **PR #629** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/629" target="_blank">Graphite</a> 
    * **PR #653** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/653" target="_blank">Graphite</a> 
    * **PR #643** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/643" target="_blank">Graphite</a> 
      * **PR #620** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/620" target="_blank">Graphite</a>  👈
    * **PR #632** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/632" target="_blank">Graphite</a> 
    * **PR #631** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/631" target="_blank">Graphite</a> 
    * **PR #630** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/630" target="_blank">Graphite</a> 
    * **PR #627** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/627" target="_blank">Graphite</a> 
      * **PR #639** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/639" target="_blank">Graphite</a> 
      * **PR #617** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/617" target="_blank">Graphite</a> 

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/620?utm_source=stack-comment).

**Comment by boneskull** [comment]
@naugtur I'm unsure if we're going to be adopting Endo's policy format, or if they will adopt ours, or what.  Here's this, anyway.  Please let me know what you think.

**Comment by naugtur** [comment]
> @naugtur I'm unsure if we're going to be adopting Endo's policy format, or if they will adopt ours, or what.  Here's this, anyway.  Please let me know what you think.

I wrote policy support in Endo to be a low level representation of something powerful enough to support our current format (via translation and setup) but also many other formats. 

One of the first steps on the path to rebuilding lavamoat-node on top of Endo is going to be a translation function and an attenuator to consume our current policy shape.

There's also a potential future where our policy allows specifying "network access" as a category that gets translated into what's needed.

**Comment by boneskull** [comment]
@naugtur Seems like it'd be good then to formalize the policy format.  

What I don't have here are things like titles and descriptions of the various properties, and that would be helpful for someone (you?) to provide so that I can fill it in:

- [ ] Title/description of entire schema.  Currently this is "LavaMoat Policy Schema"
- [ ] Title/description of `resources` prop
- [ ] Title/description of `globals`, `builtins` and `packages` within the `resources` prop
- [ ] Title/description of `resolutions` property (WIP)
- [ ] ~~Title/description of `moduleRecord` property (WIP) and its properties~~ This looks like it's part of some debugging information??

**Comment by boneskull** [comment]
Converting back to draft. Need to implement ~~`moduleRecord` and~~ `resolutions`, as well as probably add some sort of validator for testing purposes.  We can choose to validate at runtime later.

**Comment by naugtur** [comment]
We will not normalize policy between Endo and LAvamoat as their scope differs. Endo's policy is low level, while LavaMoat is aiming to be more human readable. We're hoping to one day have the ability to put more general terms in the policy that'd get translated over to the low level policy like `"network":true` for better developer experience.

So there's going to be one policy format in Endo and potentially more than one format in LavaMoat

**Comment by boneskull** [comment]
This looks OK for now.

Usually I'd want to use something like [json-schema-to-typescript](https://npm.im/json-schema-to-typescript) to generate the `.d.ts`, but it doesn't support `patternProperties` or `anyOf` very well, so I just handrolled it.

**Comment by boneskull** [comment]
Closing this and opening from new branch

**Pull request closed without merging**
