### PR TITLE
fix(viz): upgrade d3 stuff for npm audit

### PR DESCRIPTION
**Pull request by boneskull**
Supercedes #514

This is broken.

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* main
  * **PR #702** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/702" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/702?utm_source=stack-comment).

**Comment by boneskull** [comment]
Webpack just kind of dies with the updates.

**Comment by boneskull** [comment]
...well.  maybe it does work and there's something wrong with my setup.

**Comment by boneskull** [comment]
cc @legobeat

**Review by leotm — APPROVED** [review]
before: 8 high severity vulnerabilities
after: found 0 vulnerabilities 🎉

nb: `npm install` showing few `package-lock.json` [diffs](https://github.com/LavaMoat/LavaMoat/assets/1881059/ff97e8df-8c5c-4e61-992b-a045a31adda9)
but happening in `main`, so unrelated to this pr

**Pull request merged**
