### PR TITLE
feat: ignore vscode dir

### PR DESCRIPTION
**Pull request by weizman**

### CODE REVIEW

**Review by leotm — APPROVED** [review]

**Comment by boneskull** [comment]
@weizman What prompted this?

**Comment by weizman** [comment]
my vscode

**Comment by boneskull** [comment]
@weizman So, your workspace-specific settings, or launch / task configurations?  If they are useful, we should share them.

**Comment by weizman** [comment]
not really, i don't use vscode, but i wanted to use it for this one specific thing and then the file was created and not ignored so i though it'll be helpful

**Pull request merged**
