### PR TITLE
chore: fix package.json files

### PR DESCRIPTION
**Pull request by boneskull**
This is the result of running `npm pkg fix` (npm v10+) on each workspace `package.json` file. Also adds a missing `repository` field to the root workspace `package.json`.

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #818** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/818?utm_source=stack-comment-icon" target="_blank">Graphite</a> 
    * **PR #819** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/819?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/819?utm_source=stack-comment).

**Review by legobeat — APPROVED** [review]

**Review by leotm — COMMENTED** [review]
worth commiting `npm pkg fix` when run in our root workspace too?

Screenshot 2024-01-03 at 12 11 18 pm

edit: just realised this is removing dupe config, so worth commiting

**Review by leotm — APPROVED** [review]
> worth commiting `npm pkg fix` when run in our root workspace too?
> 
> Screenshot 2024-01-03 at 12 11 18 pm
> edit: just realised this is removing dupe config, so worth commiting

also spotted our vscode codeActionsOnSave (fixAll/formatDocument) keeps dupe config when saving/commiting 🤔

Screenshot 2024-01-03 at 1 41 31 pm

so i just ran `npm pkg fix` first instead, then saved to format the file 2nd, which looks correct now

**Comment by boneskull** [comment]
@leotm I don't understand if there's anything actionable here, per your comments.  

`npm pkg fix` is seemingly not a thing that VS Code can do via `codeActionsOnSave`.  There may be an extension for it.  Regardless, `prettier` should be formatting on save and as a pre-commit hook (run `npm run setup` if you don't have the hooks installed).

**Comment by leotm** [comment]
> @leotm I don't understand if there's anything actionable here, per your comments.

updating the branch (via rebase) removed my commit :(
created follow-up PR here
- https://github.com/LavaMoat/LavaMoat/pull/833

the line range (61-103) seemed too wide to comment in a GH suggestion

**Comment by leotm** [comment]
> `npm pkg fix` is seemingly not a thing that VS Code can do via `codeActionsOnSave`. There may be an extension for it. Regardless, `prettier` should be formatting on save and as a pre-commit hook (run `npm run setup` if you don't have the hooks installed).

ah i see, saving the file is simply formatting (updating order), not removing dupe config (`npm pkg fix`)

**Pull request merged**
