### PR TITLE
Ci lint

### LINKED ISSUE #31: lint is not configured correctly
it currently ignores all files

### PR DESCRIPTION
**Pull request by EtDu**
Configure standard lint properly and fix errors 
Fixes #31

### CODE REVIEW

**Comment by kumavis** [comment]
@EtDu why did you make this change? `fix utf-8 in filepath`

**Comment by EtDu** [comment]
> @EtDu why did you make this change? `fix utf-8 in filepath`

Lint yelled for not using `path.join` instead of `+` so I changed it, then it gave me an error because `utf-8` was showing up in the file path, then I changed it back and lint ignored it

**Comment by kumavis** [comment]
removing the `utf8` argument results in the fs call returning a buffer instead of a string, so that would have caused the breakage. lint is correct about `path.join` (for platform agnosticism), i think the issue is that you accidentally added `'utf8'` to the path argument, not the last encoding argument

**Review by kumavis — APPROVED** [review]

**Comment by kumavis** [comment]
noice

**Pull request merged**
