### PR TITLE
chore: remove lerna

### LINKED ISSUE #704: ditch lerna
I think we can ditch lerna for publishing.  `npm --workspaces publish` seems to work pretty well. Update docs and scripts.

### PR DESCRIPTION
**Pull request by boneskull**
This removes Lerna entirely. Publishing now happens via `npm`. Stub test scripts removed.
  
Closes #704

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* main
  * **PR #706** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/706" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/706?utm_source=stack-comment).

**Review by naugtur — APPROVED** [review]
Awesome!

**Comment by naugtur** [comment]
Have you verified whether it's going to attempt publishing already published packages or has logic to skip that?

**Comment by boneskull** [comment]
hmm...

**Comment by boneskull** [comment]
@naugtur So, yeah, `npm publish` won't check to see if the thing is already published.  We could either a) keep lerna or b) write a wrapper script to check which workspaces haven't yet been published and then only publish those. b _seems_ easy...

**Comment by naugtur** [comment]
Somehow, when I ran publishing, lerna bumped things by 2 minor versions. Not just tofu, but it did that to all packages. eg. lavapack https://www.npmjs.com/package/@lavamoat/lavapack?activeTab=versions
I'd rather have something simpler in place that is not capable of changing anything.

**Comment by boneskull** [comment]
Closed in lieu of #727

**Pull request closed without merging**
