### PR TITLE
Path based policy

### PR DESCRIPTION
**Pull request by bentobox19**
- [x] Implement path based policy
  - [x] Automatic generation of policies  (`auto` command on allow-scripts).
  - [x] Running of allowed scripts  (`run` command on allow-scripts).
- [x] Cleanup of dead code.
- [x] Tests of functionalities

### CODE REVIEW

**Comment by kumavis** [comment]
we can bring this package naming convention to other parts of lavamoat in a separate PR

**Comment by kumavis** [comment]
just need tests here

**Comment by bentobox19** [comment]
Running this in the MetaMask extension to appreciate the effects

### Before

```js
  "lavamoat": {
    "allowScripts": {
      "@lavamoat/preinstall-always-fail": false,
      "@sentry/cli": false,
      "core-js": false,
      "fsevents": false,
      "core-js-pure": false,
      "chromedriver": false,
      "keccak": false,
      "secp256k1": false,
      "web3": false,
      "sha3": false,
      "bufferutil": false,
      "utf-8-validate": false,
      "geckodriver": false,
      "electron": false,
      "leveldown": false,
      "ursa-optional": false,
      "gc-stats": false,
      "github:assemblyscript/assemblyscript": false,
      "tiny-secp256k1": false,
      "node-hid": false,
      "usb": false,
      "gridplus-sdk": false
    }
  }
```

#### Now

 ```js
 "lavamoat": {
    "allowScripts": {
      "ethereumjs-tx/keccak": false,
      "leveldown": false,
      "ganache-core/eth-json-rpc-middleware/keccak": false,
      "ganache-core/eth-block-tracker/keccak": false,
      "ganache-core/web3": false,
      "ganache-core/keccak": false,
      "ganache-core/web3-provider-engine/keccak": false,
      "ganache-core/eth-sig-util/keccak": false,
      "ganache-core/ethereumjs-vm/keccak": false,
      "ganache-core/merkle-patricia-tree/keccak": false,
      "eth-json-rpc-middleware/keccak": false,
      "ganache-cli/keccak": false,
      "ganache-cli/secp256k1": false,
      "orbit-db-cache/leveldown": false,
      "lazy-universal-dotenv/core-js": false,
      "@sentry/cli": false,
      "sha3": false,
      "global-agent/core-js": false,
      "assemblyscript": false,
      "eth-tx-summary/keccak": false,
      "babel-register/core-js": false,
      "eth-trezor-keyring/keccak": false,
      "core-js-pure": false,
      "@lavamoat/preinstall-always-fail": false,
      "chokidar/fsevents": false,
      "ethereumjs-blockchain/keccak": false,
      "ethereum-cryptography/secp256k1": false,
      "ipld-ethereum/keccak": false,
      "gridplus-sdk": false,
      "gridplus-sdk/secp256k1": false,
      "eth-json-rpc-filters/keccak": false,
      "keccak": false,
      "web3-provider-engine/keccak": false,
      "core-js": false,
      "geckodriver": false,
      "secp256k1": false,
      "usb": false,
      "@metamask/eth-ledger-bridge-keyring/keccak": false,
      "ursa-optional": false,
      "utf-8-validate": false,
      "ethereumjs-block/keccak": false,
      "node-hid": false,
      "bufferutil": false,
      "chromedriver": false,
      "ethereumjs-account/keccak": false,
      "eth-sig-util/keccak": false,
      "@storybook/ui/core-js-pure": false,
      "@storybook/semver/core-js": false,
      "babel-runtime/core-js": false,
      "electron": false,
      "@ledgerhq/hw-transport-node-hid-noevents/node-hid": false,
      "merkle-patricia-tree/keccak": false,
      "eth-json-rpc-infura/keccak": false,
      "tiny-secp256k1": false,
      "gc-stats": false
    }
  }
 ```

**Comment by kumavis** [comment]
### shortest logical path
```json
{
"allowScripts": {
      "3box>3box-orbitdb-plugins>ipfs-log>orbit-db-identity-provider>orbit-db-keystore>leveldown": false,
      "3box>3box-orbitdb-plugins>ipfs-log>orbit-db-identity-provider>orbit-db-keystore>libp2p-crypto>libp2p-crypto-secp256k1>secp256k1": false,
      "3box>3box-orbitdb-plugins>ipfs-log>orbit-db-identity-provider>orbit-db-keystore>libp2p-crypto>ursa-optional": false,
      "3box>ipfs>ipfs-mfs>ipfs-unixfs-exporter>ipfs-unixfs-importer>rabin-wasm>assemblyscript": false,
      "3box>ipfs>ipld-bitcoin>bitcoinjs-lib>bip32>tiny-secp256k1": false,
      "3box>ipfs>ipld-ethereum>ethereumjs-account>ethereumjs-util>keccak": false,
      "3box>ipfs>ipld-ethereum>ethereumjs-block>ethereumjs-tx>ethereumjs-util>ethereum-cryptography>keccak": false,
      "3box>ipfs>ipld-ethereum>ethereumjs-block>ethereumjs-tx>ethereumjs-util>ethereum-cryptography>secp256k1": false,
      "3box>ipfs>ipld-ethereum>ethereumjs-block>ethereumjs-util>keccak": false,
      "3box>ipfs>ipld-ethereum>ethereumjs-block>merkle-patricia-tree>ethereumjs-util>keccak": false,
      "3box>ipfs>ipld-ethereum>ethereumjs-tx>ethereumjs-util>keccak": false,
      "3box>ipfs>ipld-ethereum>merkle-patricia-tree>ethereumjs-util>keccak": false,
      "3box>orbit-db>orbit-db-cache>leveldown": false,
      "@keystonehq/bc-ur-registry-eth>hdkey>secp256k1": false,
      "@lavamoat/allow-scripts>@lavamoat/preinstall-always-fail": false,
      "@metamask/controllers>babel-runtime>core-js": false,
      "@metamask/controllers>eth-json-rpc-infura>eth-json-rpc-middleware>eth-sig-util>ethereumjs-util>keccak": false,
      "@metamask/controllers>eth-keyring-controller>eth-hd-keyring>eth-sig-util>ethereumjs-util>keccak": false,
      "@metamask/controllers>web3-provider-engine>eth-json-rpc-filters>eth-json-rpc-middleware>eth-sig-util>ethereumjs-util>keccak": false,
      "@metamask/controllers>web3-provider-engine>eth-json-rpc-middleware>eth-sig-util>ethereumjs-util>keccak": false,
      "@metamask/eth-ledger-bridge-keyring>eth-sig-util>ethereumjs-util>keccak": false,
      "@sentry/cli": false,
      "@storybook/addon-a11y>@storybook/addons>@storybook/api>@storybook/channels>core-js": false,
      "@storybook/addon-essentials>@storybook/addon-docs>@storybook/builder-webpack4>@storybook/ui>core-js-pure": false,
      "chromedriver": false,
      "eth-json-rpc-middleware>eth-sig-util>ethereumjs-util>keccak": false,
      "eth-lattice-keyring>gridplus-sdk": false,
      "eth-lattice-keyring>gridplus-sdk>secp256k1": false,
      "ganache-cli>ethereumjs-util>ethereum-cryptography>keccak": false,
      "ganache-cli>ethereumjs-util>ethereum-cryptography>secp256k1": false,
      "ganache-core>eth-sig-util>ethereumjs-util>keccak": false,
      "ganache-core>ethereumjs-vm>ethereumjs-blockchain>ethereumjs-util>keccak": false,
      "ganache-core>ethereumjs-vm>merkle-patricia-tree>ethereumjs-util>keccak": false,
      "ganache-core>keccak": false,
      "ganache-core>merkle-patricia-tree>ethereumjs-util>keccak": false,
      "ganache-core>web3": false,
      "ganache-core>web3-provider-engine>eth-block-tracker>ethereumjs-tx>ethereumjs-util>keccak": false,
      "ganache-core>web3-provider-engine>eth-block-tracker>json-rpc-engine>babelify>babel-core>babel-register>core-js": false,
      "ganache-core>web3-provider-engine>eth-json-rpc-infura>eth-json-rpc-middleware>eth-tx-summary>ethereumjs-block>ethereumjs-util>keccak": false,
      "ganache-core>web3-provider-engine>eth-json-rpc-infura>eth-json-rpc-middleware>ethereumjs-block>ethereumjs-tx>ethereumjs-util>keccak": false,
      "ganache-core>web3-provider-engine>eth-sig-util>ethereumjs-util>keccak": false,
      "ganache-core>web3>web3-bzz>swarm-js>eth-lib>keccakjs>sha3": false,
      "ganache-core>web3>web3-core>web3-core-requestmanager>web3-providers-ws>websocket>bufferutil": false,
      "ganache-core>web3>web3-core>web3-core-requestmanager>web3-providers-ws>websocket>utf-8-validate": false,
      "geckodriver": false,
      "react-devtools>electron": false
    }
 }
```

**Pull request merged**
