### PR TITLE
feat(endomoat): policy generation implementation

### PR DESCRIPTION
**Pull request by boneskull**
This branch is for @naugtur and I to collaborate on policy-gen changes.

## Setup

1. Checkout PR https://github.com/endojs/endo/pull/2190  in a working copy of `endojs/endo`
2. Run `yarn` to update deps, etc.
3. Run this: 
    ```sh
    npx lerna build:types && \ 
    npm link -w @endo/compartment-mapper -w ses -w @endo/env-options -w @endo/cjs-module-analyzer \
      -w @endo/static-module-record -w @endo/zip
    ```
4. Navigate to your `LavaMoat/LavaMoat` working copy.
5. Run this:
    ```sh
    npm ci && \
    npm link @endo/compartment-mapper ses @endo/env-options @endo/cjs-module-analyzer \
      @endo/static-module-record @endo/zip -w packages/endomoat && \
    npm run rebuild:types # verify linking
    ```

**The above will only work properly if all versions of `@endo/compartment-mapper` are the same**; run `npm ls @endo/compartment-mapper` to verify this.  If this isn't the case, deduping won't occur upon linking, and the type generation will fail.

> [!NOTE]
>
> If you find linking fails because `ses`' `prepare` script doesn't work, delete the `prepare` script from its `package.json`.

### CODE REVIEW

**Comment by boneskull** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/969?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#1076** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1076?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#969** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/969?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/969?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#772** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/772?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#1349](https://github.com/LavaMoat/LavaMoat/pull/1349) <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1349?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#1397** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1397?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#1442** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/1442?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by naugtur** [comment]
Could we have the core/tofu changes here and rebase our work on those? Otherwise, the endomoat and webpack work will be super hard to review.

**Comment by boneskull** [comment]
@naugtur If we want to rebase _this_ onto the ESM changes (#809 and #810), then:

1. We have to rebase #772 onto #810 (since this depends on #772), putting it deeper in the PR tree, _or_
2. Merge #772 and rebase #809 onto `main`, then rebase _this_ on top of #810 (which is itself targeting #809)

Since #772 does not actually need #810, we should do 2, but that'd require some approvals.

**Comment by boneskull** [comment]
CLI now looks like:

```
endomoat <entrypoint>

Run an application

Commands:
  endomoat run <entrypoint>  Run an application                        [default]
  endomoat gen <entrypoint>  Generate policy files; overwrites existing policies
                                                             [aliases: generate]

Positionals:
  entrypoint  Path to the application entry point            [string] [required]

Options:
      --help                         Show help                         [boolean]
      --version                      Show version number               [boolean]
  -p, --policy                       Filepath to a policy file
                                 [string] [default: "lavamoat/node/policy.json"]
  -o, --policy-override, --override  Filepath to a policy override file
                        [string] [default: "lavamoat/node/policy-override.json"]
      --policy-debug, --pd           Filepath to a policy debug file
                           [string] [default: "lavamoat/node/policy-debug.json"]
      --cwd                          Path to application root directory
                                         [string] [default: (current directory)]
```

_Note that `run` is the default command._ And so if we do `endomoat gen --help`:

```
endomoat gen <entrypoint>

Generate policy files; overwrites existing policies

Behavior Options:
      --run    Run the application after policy generated              [boolean]
      --debug  Additionally write a debug policy                       [boolean]

Positionals:
  entrypoint  Path to the application entry point            [string] [required]

Options:
      --help                         Show help                         [boolean]
      --version                      Show version number               [boolean]
  -p, --policy                       Filepath to a policy file
                                 [string] [default: "lavamoat/node/policy.json"]
  -o, --policy-override, --override  Filepath to a policy override file
                        [string] [default: "lavamoat/node/policy-override.json"]
      --policy-debug, --pd           Filepath to a policy debug file
                           [string] [default: "lavamoat/node/policy-debug.json"]
      --cwd                          Path to application root directory
                                         [string] [default: (current directory)]
```

Anyway. Subcommands make more sense to me than just a big bucket of options.

**Pull request closed without merging**
