### PR TITLE
chore: Regenerate generated files

### PR DESCRIPTION
**Pull request by legobeat**
Commit changes generated by:
- `npm run test:prep`
- `npm run build`

### CODE REVIEW

**Review by weizman — APPROVED** [review]

**Review by naugtur — CHANGES_REQUESTED** [review]
I think this change is invalid if we merge: https://github.com/LavaMoat/LavaMoat/pull/676

Please check if #676 overlooks any of the issues that this change addresses.

**Comment by legobeat** [comment]
> I think this change is invalid if we merge: #676
> 
> Please check if #676 overlooks any of the issues that this change addresses.

If I get this right: 
- `lavapack` changes will get replaced in #676 (so if that's merged before this one, those changes should get rebased away)
- the `node` and `browserify` changes are unrelated

**Review by boneskull — APPROVED** [review]

**Comment by boneskull** [comment]
@naugtur needs to approve this since it's blocked on his disapproval

**Comment by naugtur** [comment]
I see you've backed out of generating on the fly.
I'll unblock first and ask questions later

**Review by naugtur — APPROVED** [review]

**Pull request merged**
