### PR TITLE
chore(renovate): do not automerge anything

### PR DESCRIPTION
**Pull request by boneskull**
We can loosen this later if we feel there is too much to deal with.

### CODE REVIEW

**Comment by boneskull** [comment]
Current dependencies on/for this PR:
* `main`
  * **PR #861** <a href="https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/861?utm_source=stack-comment-icon" target="_blank">Graphite</a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/LavaMoat/LavaMoat/861?utm_source=stack-comment).

**Review by naugtur — APPROVED** [review]
not sure why, but no reason to block this

**Comment by boneskull** [comment]
I _thought_ we had agreed that we shouldn't be automerging _anything_, but maybe I'm misremembering.  Am I? @naugtur

**Review by leotm — APPROVED** [review]

**Comment by leotm** [comment]
> I _thought_ we had agreed that we shouldn't be automerging _anything_, but maybe I'm misremembering. Am I? @naugtur

just remembering our earlier [convo](https://github.com/LavaMoat/LavaMoat/pull/670#discussion_r1305611163)

> could it be worth trialing `automergePatch` first? then if things going well `automergeMinor`
> 
> only concern it could be too much automation too soon but depends how confident we are with our tests (on node 14/16/18 atm)
> 
> although it would reduce noise (fewer open PRs) and keep us more up-to-date

but not auto-merging anything for now seems safer 👍

**Pull request merged**
